### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by edaena** [edaena/ohbedrock#1]
- [x] Change name of infra scaffold component from "cluster" to "common"
- [ ] Diagram of overall system
- [x] Remove PAT instruction from Challenge 0
- [ ] Fill out glossary
- [x] Deploy azure-single-key-vault via spk
- [x] Deploy common infra via spk
- [ ] Make introspection script similar to infra script
- [x] Add info about azure-single-keyvault in challenge 1

Issue:
- [ ] use `single-key-vault` for other challenges
- [x] uncomment steps from infra-setup.sh
- [ ] add more links to official documentation (service principal setup, keyvault)
- [ ] Change challenge 1 to `azure-simple`
- [ ] Have challenge 7 setup azure single-keyvault
- [ ] Move introspection under challenge 6

Challenge 1:
- [ ] Add namespace to app
- [ ] Change flux sync time from 5m to 1m
- [x] Fix docker image versions in Challenge 1 sub-challenges
- [ ] Include overall diagram in Challenge 1
- [ ] Check if environment variables are still needed

Challenge 2:
- [ ] Pending: verify services bug fix to automatically update image.tag in the hld repo
- [ ] Add instructions to change the flux deployment `gitops_path` value, if the directory in the manifest repo changes (`kubectl edit deployment flux -n flux`)

Test:
- [x] Run through challenge 1 again
- [x] Change image tag from the manifest repo
- [ ] Run through challenge 1 in wsl

- [ ] Check all documentation links work before OH
